### PR TITLE
Fixing issues #33 and #34 about allowed headers in H2 protocol

### PR DESCRIPTION
**Pull request by mykiimike**
If you want to merge.
It fixes my problem on iOS device using H2 protocol.

mykii-

### CODE REVIEW

**Comment by pavel** [comment]
@indutny Can you please merge this one?

**Comment by indutny** [comment]
Landed in 9c19a09, and released in 2.0.18. Sorry for delay!

**Comment by pavel** [comment]
No worries. Thanks a lot!

**Comment by mykiimike** [comment]
Thanks for the merge

**Comment by indutny** [comment]
No problem, really sorry to delay it for so long.

**Pull request closed without merging**
